(function(){
'use strict';
const E=window.SortirCairanMesin,K=window.DehayukKit,T=window.SortirCairanTuang,SLUG='sortir-cairan',ST=K.store(SLUG),Q=new URLSearchParams(location.search),$=id=>document.getElementById(id);
const COLORS=[['#37ddff','#168ddd','Biru muda'],['#ff79b8','#e62c84','Merah muda'],['#ffe55a','#efad17','Kuning'],['#68efb3','#1cbd8c','Hijau'],['#b18bff','#7648e1','Ungu'],['#ffb16a','#ed692d','Jingga'],['#ff737d','#d9315f','Merah'],['#79a0ff','#335dde','Biru tua']];
const ICONS={daily:'<rect x="4" y="5" width="16" height="16" rx="4"/><path d="M8 3v4M16 3v4M4 10h16m-10 4 2 2 4-4"/>',share:'<circle cx="6" cy="12" r="3"/><circle cx="18" cy="5" r="3"/><circle cx="18" cy="19" r="3"/><path d="m9 10 6-4M9 14l6 4"/>',settings:'<path d="m10 3-1 3-3 1-2 3 2 2-1 3 3 3 3-1 2 2 3-2 1-3 3-1v-4l-3-1-1-3-3-2Z"/><circle cx="12" cy="12" r="3"/>',undo:'<path d="M9 5 3 11l6 6M3 11h11a6 6 0 0 1 0 12" transform="translate(1 -2)"/>',hint:'<path d="M8 15a7 7 0 1 1 8 0v3H8Zm1 6h6M12 2V0M3 5 1 3M21 5l2-2"/>',restart:'<path d="M5 8a8 8 0 1 1-1 8M4 3v6h6"/>'};
document.querySelectorAll('[data-icon]').forEach(n=>n.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true">'+ICONS[n.dataset.icon]+'</svg>');
$('paints').innerHTML=COLORS.map((c,i)=>'<linearGradient id="p'+i+'" x1="0" y1="0" x2="1" y2="0"><stop stop-color="'+c[1]+'"/><stop offset=".32" stop-color="'+c[0]+'"/><stop offset=".68" stop-color="'+c[0]+'"/><stop offset="1" stop-color="'+c[1]+'"/></linearGradient>').join('');
let seq=0,mode='title',kind='normal',level=1,seed=1,generated=null,board=[],moves=0,hints=0,undos=0,history=[],selected=-1,busy=false,epoch=0,pourJob=null,lastResult=null,returnFocus=null,hintTo=-1,hintTimer=0,countTimer=0;
let runDate=K.dateKey(),saveOk=true;
let pourMotion=ST.get('pourMotion',null);
const fullPour=()=>pourMotion==null?!reduced():!!pourMotion;
let patterns=!!ST.get('patterns',false),challenge=K.readChallenge();
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function liquidMarkup(a,fill,angle,prepared){
  const units=fill==null?a.length:fill,tilt=angle||0,layers=prepared||T.layers(a,units,tilt);
  return layers.map((layer,i)=>{
    const points=layer.points.map(p=>p[0].toFixed(3)+','+p[1].toFixed(3)).join(' ');
    let markup='<polygon class="liquid-band" data-color="'+layer.color+'" data-units="'+layer.units+'" points="'+points+'" fill="url(#p'+layer.color+')"/>';
    if(patterns&&layer.units>.75&&layer.points.length){
      const center=layer.points.reduce((p,v)=>[p[0]+v[0]/layer.points.length,p[1]+v[1]/layer.points.length],[0,0]);
      markup+='<text x="'+center[0]+'" y="'+(center[1]+5)+'" transform="rotate('+(-tilt)+' '+center[0]+' '+center[1]+')" font-family="Nunito,Arial" text-anchor="middle" font-size="16" font-weight="900" fill="#35184e" opacity=".8">'+(layer.color+1)+'</text>';
    }
    if(i===layers.length-1&&layer.surface){const [p,q]=layer.surface;markup+='<path class="liquid-surface" d="M'+p[0]+' '+p[1]+'L'+q[0]+' '+q[1]+'" stroke="white" stroke-width="2" opacity=".35" fill="none"/>';}
    return markup;
  }).join('');
}
function bottleSVG(a,fill){const id='jar'+(++seq),done=a.length===4&&a.every(c=>c===a[0]);return '<svg viewBox="0 0 100 220" aria-hidden="true"><defs><clipPath id="'+id+'"><path d="M39 12V40Q39 48 27 56Q24 59 24 70V183Q24 200 42 200H58Q76 200 76 183V70Q76 59 73 56Q61 48 61 40V12Z"/></clipPath></defs><ellipse class="ground-shadow" cx="50" cy="213" rx="32" ry="5" fill="'+(done?'#b8f2b6':'#130520')+'" opacity="'+(done?'.25':'.32')+'"/><path d="M39 12V39Q39 46 27 54Q22 58 22 70V184Q22 203 41 203H59Q78 203 78 184V70Q78 58 73 54Q61 46 61 39V12Z" fill="#c0d4ff" fill-opacity=".10" stroke="#e6d5ff" stroke-opacity=".75" stroke-width="2.5"/><g class="liquids" data-units="'+(fill==null?a.length:fill)+'" clip-path="url(#'+id+')">'+liquidMarkup(a,fill)+'</g><path d="M32 66V177Q32 188 39 190" fill="none" stroke="white" stroke-width="4" opacity=".38"/><path d="M69 70v110" fill="none" stroke="#ffffff" stroke-width="2" opacity=".13"/><path d="M43 22v16q0 13-12 21" fill="none" stroke="#fff" stroke-width="3" opacity=".4"/><rect x="36" y="8" width="28" height="8" rx="3" fill="#8064a6" stroke="#e6d5ff" stroke-width="2"/><ellipse cx="50" cy="10" rx="11" ry="2" fill="#2b183f"/>'+(done?'<path d="m50 72 4 8 9 1-7 6 2 9-8-5-8 5 2-9-7-6 9-1Z" fill="#fff285" stroke="#a86f2a" stroke-width="1.5"/>':'')+'</svg>';}
$('hero').innerHTML=[[2,0,1,1],[0,2,2,0],[1,1,2,2],[3,0,3,3],[0,3,1,0]].map(a=>bottleSVG(a)).join('');
function playSound(win){K.audio.unlock();if(win)K.audio.chord([523,659,784,1047],{dur:.3,vol:.18,stagger:.09});else K.audio.tone({freq:560,dur:.06,vol:.12,slideTo:840});}
function freshSeed(l){return ((Math.min(255,l)<<24)|(Math.random()*16777216|0))>>>0;}
function seedLevel(s){return Math.max(1,Math.min(255,s>>>24));}
function boundedLevel(l){return Math.max(1,Math.min(255,Math.floor(+l)||1));}
function key(){return 'active-'+kind;}
function save(){if(!generated||mode==='result'||!board.length)return;saveOk=ST.set(key(),{v:1,kind,level,seed,date:runDate,board:E.clone(board),moves,hints,undos,history:history.slice(-18).map(E.clone)});}
function validSaved(r){if(!r||r.v!==1||!['normal','daily','practice','chal'].includes(r.kind)||!Number.isInteger(r.level)||r.level<1||r.level>255||!Number.isInteger(r.seed)||r.seed<1||r.seed>4294967295||!Array.isArray(r.board)||!Array.isArray(r.history)||r.history.length>18)return false;if(['daily','practice'].includes(r.kind)&&r.date!==K.dateKey())return false;let g=E.generate(r.level,r.seed);const valid=a=>Array.isArray(a)&&a.length===g.colors+2&&a.every(t=>Array.isArray(t)&&t.length<=4&&t.every(c=>Number.isInteger(c)&&c>=0&&c<g.colors))&&Array.from({length:g.colors},(_,c)=>a.flat().filter(v=>v===c).length).every(n=>n===4);return valid(r.board)&&!E.isSolved(r.board)&&r.history.every(valid)&&['moves','hints','undos'].every(k=>Number.isInteger(r[k])&&r[k]>=0&&r[k]<=1000000);}
function readSaved(k,s){const r=ST.get('active-'+k,null);return validSaved(r)&&r.kind===k&&(s==null||r.seed===s)?r:null;}
function say(text){$('status').textContent=text;}
function hideSheets(){$('sheet').hidden=true;$('result').hidden=true;clearInterval(countTimer);}
function finishPour(){if(pourJob)pourJob.finish();}
function title(){finishPour();save();epoch++;clearTimeout(hintTimer);busy=false;mode='title';selected=-1;hideSheets();$('playScreen').hidden=true;$('titleScreen').hidden=false;const p=K.progress.get();$('progressChip').textContent='Lv '+p.level+'  \u00b7  '+p.streak+' hari';$('bestChip').textContent='\u2605 '+ST.get('best',0);const resume=challenge?readSaved('chal',challenge.seed):readSaved('normal');$('bMain').textContent=challenge?'MAIN TANTANGAN':resume?'LANJUTKAN':'MAIN';$('mainNote').textContent=challenge?'Kalahkan skor teman: '+challenge.score:resume?'Level '+resume.level+' tersimpan. Lanjut kapan saja.':'Ketuk botol, lalu pilih tempat menuang.';}
function start(k,l,s,resume){finishPour();epoch++;clearTimeout(hintTimer);if(kind==='daily'&&k==='practice')ST.set('active-daily',null);kind=k;runDate=resume?resume.date:K.dateKey();level=boundedLevel(l);seed=s>>>0;generated=E.generate(level,seed);board=resume?E.clone(resume.board):E.clone(generated.board);moves=resume?resume.moves:0;hints=resume?resume.hints:0;undos=resume?resume.undos:0;history=resume?resume.history.map(E.clone):[];selected=-1;hintTo=-1;busy=false;mode='play';hideSheets();$('titleScreen').hidden=true;$('playScreen').hidden=false;updateHUD();render();say(resume?'Permainan tersimpan sudah dilanjutkan.':'Pilih botol, lalu tuang ke warna yang sama atau botol kosong.');save();K.music.start({step:.24,root:48,melody:[7,-1,5,-1,4,-1,3,-1,5,-1,4,-1,2,-1,-1,-1]});}
function main(){playSound();if(challenge){const r=readSaved('chal',challenge.seed);start('chal',seedLevel(challenge.seed),challenge.seed,r);return;}const r=readSaved('normal');if(r)start('normal',r.level,r.seed,r);else{let l=boundedLevel(ST.get('level',1));start('normal',l,freshSeed(l));}}
function updateHUD(){$('levelLabel').textContent=kind==='daily'?'Harian':kind==='practice'?'Latihan Harian':kind==='chal'?'Tantangan':'Level '+level;$('kindLabel').textContent=generated.colors+' warna \u00b7 '+(kind==='chal'?'target '+challenge.score:'tanpa batas waktu');$('movesLabel').textContent=moves;$('bUndo').disabled=busy||!history.length;$('bHint').disabled=busy;$('bRestart').disabled=busy;}
function render(){if(!$('board').clientHeight)return;const focused=document.activeElement&&document.activeElement.closest('#board [data-i]'),focusIndex=focused?+focused.dataset.i:-1;const box=$('board'),w=box.clientWidth,h=box.clientHeight,n=board.length,cols=w>700?(n<=7?n:Math.ceil(n/2)):n<=5?3:n<=8?4:5,rows=Math.ceil(n/cols),headroom=56,gap=rows>1?25:15,cellW=Math.min(w/cols,130),cellH=Math.min((h-headroom-gap*(rows-1))/rows,258),bw=Math.max(44,Math.min(cellW-8,(cellH-19)*100/220)),bh=bw*2.2+19,totalH=rows*bh+(rows-1)*gap,top=Math.max(headroom,headroom+(h-headroom-totalH)/2);box.innerHTML=board.map((a,i)=>{const row=Math.floor(i/cols),count=Math.min(cols,n-row*cols),x=(w-count*cellW)/2+(i%cols)*cellW+(cellW-bw)/2,y=top+row*(bh+gap),legal=selected>=0&&E.pour(board,selected,i),label='Botol '+(i+1)+': '+(a.length?a.slice().reverse().map(c=>COLORS[c][2]).join(', ')+', dari atas':'kosong');return '<button class="bottle'+(selected===i?' selected':'')+(legal?' available':'')+(hintTo===i?' hinted':'')+'" data-i="'+i+'" style="left:'+x+'px;top:'+y+'px;width:'+bw+'px;height:'+bh+'px" aria-label="'+label+'" aria-pressed="'+(selected===i)+'">'+bottleSVG(a)+'<small>'+(i+1)+'</small></button>';}).join('');updateHUD();if(focusIndex>=0){const b=box.querySelector('[data-i="'+focusIndex+'"]');if(b)b.focus({preventScroll:true});}}
function blocked(){return mode!=='play'||busy||!$('sheet').hidden||!$('result').hidden||!!document.querySelector('.dk-overlay:not([hidden])');}
function select(i){if(blocked())return;K.audio.unlock();hintTo=-1;if(selected===i){selected=-1;render();say('Pilih botol yang ingin kamu tuang.');return;}if(selected<0){if(!board[i].length){say('Botol ini kosong. Pilih botol yang berisi cairan dulu.');return;}selected=i;playSound();render();say('Sekarang pilih botol kosong atau warna atas yang sama.');return;}const from=selected,res=E.pour(board,from,i);if(!res){let b=$('board').querySelector('[data-i="'+i+'"]');b.classList.add('shake');setTimeout(()=>b.classList.remove('shake'),300);say(board[i].length===4?'Botol ini penuh. Pilih botol lain.':'Warna paling atas harus sama, atau pilih botol kosong.');K.vibrate(16);return;}history.push(E.clone(board));if(history.length>18)history.shift();const before=E.clone(board);board=res.board;moves++;selected=-1;busy=true;updateHUD();say('Menuangkan '+COLORS[res.color][2].toLowerCase()+'...');save();animatePour(before,from,i,res);}
function animatePour(before,from,to,res){
  const token=epoch,source=$('board').querySelector('[data-i="'+from+'"]'),target=$('board').querySelector('[data-i="'+to+'"]');
  const sr=source.querySelector('svg').getBoundingClientRect(),tr=target.querySelector('svg').getBoundingClientRect(),boardBox=$('board').getBoundingClientRect();
  const viewport={width:innerWidth,height:innerHeight},plan=T.plan(sr,tr,viewport),rest={x:boardBox.x+source.offsetLeft+sr.width/2,y:boardBox.y+source.offsetTop+sr.height*10/220};
  const calm=!fullPour(),approach=calm?100:270,tiltTime=calm?0:170,flowTime=640+res.count*100,dripTime=100,returnTime=calm?140:290,flowStart=approach+tiltTime,flowEnd=flowStart+flowTime,duration=flowEnd+dripTime+returnTime;
  const clamp=v=>Math.max(0,Math.min(1,v)),ease=v=>{v=clamp(v);return v<.5?4*v*v*v:1-Math.pow(-2*v+2,3)/2;},mix=(a,b,f)=>a+(b-a)*f;
  let raf=0,done=false,lastNoise=-1000,elapsed=0,lastFrame=performance.now();
  const clone=document.createElement('div');clone.className='pour-clone';clone.setAttribute('aria-hidden','true');clone.dataset.from=from;clone.dataset.to=to;
  clone.style.cssText='left:'+sr.x+'px;top:'+sr.y+'px;width:'+sr.width+'px;height:'+sr.height+'px;transform-origin:50% '+(sr.height*10/220)+'px';clone.innerHTML=bottleSVG(before[from]);
  const shadow=clone.querySelector('.ground-shadow');if(shadow)shadow.remove();
  document.body.appendChild(clone);
  const stream=document.createElementNS('http://www.w3.org/2000/svg','svg');stream.setAttribute('class','pour-stream');stream.setAttribute('aria-hidden','true');stream.setAttribute('viewBox','0 0 '+innerWidth+' '+innerHeight);
  stream.innerHTML='<path class="stream-back" stroke="'+COLORS[res.color][1]+'"/><path class="stream-core" stroke="'+COLORS[res.color][0]+'"/><path class="stream-shine" stroke="#fff9dd" opacity=".52"/><circle class="pour-drop" r="2.5" fill="'+COLORS[res.color][0]+'"/>';
  document.body.appendChild(stream);
  source.style.visibility='hidden';target.classList.add('receiving');
  const sourceLiquid=clone.querySelector('.liquids'),targetLiquid=target.querySelector('.liquids');
  const finish=()=>{
    if(done)return;done=true;cancelAnimationFrame(raf);clone.remove();stream.remove();source.style.visibility='';target.classList.remove('receiving');delete target.dataset.fill;pourJob=null;
    if(token!==epoch)return;
    busy=false;render();playSound();
    if(E.isSolved(board))complete();else{const full=board[to].length===4&&board[to].every(c=>c===board[to][0]);say(full?'Satu botol sudah rapi! Lanjutkan warna lainnya.':'Bagus! Pilih cairan berikutnya.');save();}
  };
  pourJob={finish};
  function paint(el,colors,units,angle){const layers=T.layers(colors,units,angle);el.innerHTML=liquidMarkup(colors,units,angle,layers);el.dataset.units=units;return layers;}
  function frame(now){
    if(done)return;
    elapsed=Math.min(duration,elapsed+Math.min(80,Math.max(0,now-lastFrame)));lastFrame=now;
    const progress=clamp(elapsed/duration),fraction=clamp((elapsed-flowStart)/flowTime),remaining=before[from].length-res.count*fraction,filled=before[to].length+res.count*fraction;
    let angle=0,x=plan.from.x,y=plan.from.y,opacity=1,phase='approach';
    if(calm){x=plan.to.x;y=plan.to.y;angle=plan.angle;opacity=elapsed<flowStart?ease(elapsed/approach):elapsed>flowEnd+dripTime?1-ease((elapsed-flowEnd-dripTime)/returnTime):1;phase=elapsed<flowStart?'approach':elapsed<flowEnd?'flow':'return';}
    else if(elapsed<approach){const f=ease(elapsed/approach);x=mix(plan.from.x,plan.to.x,f);y=mix(plan.from.y,plan.to.y,f)-Math.sin(Math.PI*f)*22;angle=plan.angle*.48*f;}
    else if(elapsed<flowStart){const f=ease((elapsed-approach)/tiltTime);x=plan.to.x;y=plan.to.y;angle=mix(plan.angle*.48,plan.angle,f);phase='tilt';}
    else if(elapsed<flowEnd+dripTime){x=plan.to.x;y=plan.to.y;angle=plan.angle;phase=elapsed<flowEnd?'flow':'drip';}
    else{const f=ease((elapsed-flowEnd-dripTime)/returnTime);x=mix(plan.to.x,rest.x,f);y=mix(plan.to.y,rest.y,f)-Math.sin(Math.PI*f)*28;angle=plan.angle*(1-f);phase='return';}
    const rad=angle*Math.PI/180,s=Math.sin(rad),c=Math.cos(rad),corners=[[18,6],[82,6],[82,205],[18,205]].map(p=>{const px=(p[0]-50)*sr.width/100,py=(p[1]-10)*sr.height/220;return [px*c-py*s,px*s+py*c];});
    const left=Math.min(...corners.map(p=>p[0])),right=Math.max(...corners.map(p=>p[0])),top=Math.min(...corners.map(p=>p[1])),bottom=Math.max(...corners.map(p=>p[1]));
    x=Math.max(8-left,Math.min(viewport.width-8-right,x));y=Math.max(8-top,Math.min(viewport.height-8-bottom,y));
    clone.style.transform='translate('+(x-plan.from.x)+'px,'+(y-plan.from.y)+'px) rotate('+angle+'deg)';clone.style.opacity=opacity;
    clone.dataset.angle=angle;clone.dataset.progress=progress;clone.dataset.phase=phase;clone.dataset.fill=remaining;clone.dataset.mouthX=x;clone.dataset.mouthY=y;target.dataset.fill=filled;
    const sourceLayers=paint(sourceLiquid,before[from],remaining,angle),targetLayers=paint(targetLiquid,res.board[to],filled,0);
    // The outgoing top color follows a film along the inner wall to the neck.
    // Gravity still keeps the bulk liquid level horizontal while this color drains.
    const neckAmount=clamp((Math.abs(angle)-62)/28)*clamp((flowEnd-elapsed)/65);
    if(neckAmount>0&&remaining>before[from].length-res.count+.002){
      const topLayer=sourceLayers.at(-1),points=topLayer?topLayer.points:[],entry=points.reduce((best,p)=>Math.hypot(p[0]-70,p[1]-48)<Math.hypot(best[0]-70,best[1]-48)?p:best,points[0]||[65,120]);
      sourceLiquid.insertAdjacentHTML('beforeend','<path class="source-outflow" d="M'+entry[0]+' '+entry[1]+'Q73 '+Math.max(64,entry[1]*.7)+' 71 64Q68 50 56 40L56 12" fill="none" stroke="'+COLORS[res.color][0]+'" stroke-width="6" stroke-linecap="round" opacity="'+neckAmount+'"/><path class="source-neck" d="M39 12H61V40H39Z" fill="url(#p'+res.color+')" opacity="'+neckAmount+'"/>');
    }
    const flowing=elapsed>=flowStart&&elapsed<flowEnd,opening={x:tr.x+tr.width/2,y:tr.y+tr.height*10/220},wave=Math.sin(now*.026);
    stream.style.opacity=flowing?1:0;stream.dataset.startX=x;stream.dataset.startY=y;stream.dataset.endX=opening.x;stream.dataset.endY=opening.y;
    if(flowing){
      const thickness=Math.max(4,sr.width*.065)*(1+.05*wave),d='M'+x+' '+y+'Q'+(opening.x+wave*1.3)+' '+mix(y,opening.y,.5)+' '+opening.x+' '+opening.y;
      const paths=stream.querySelectorAll('path');paths.forEach(p=>p.setAttribute('d',d));paths[0].setAttribute('stroke-width',thickness+2);paths[1].setAttribute('stroke-width',thickness);paths[2].setAttribute('stroke-width',Math.max(1,thickness*.18));
      const topLayer=targetLayers.at(-1),surface=topLayer&&topLayer.surface,surfaceY=surface?(surface[0][1]+surface[1][1])/2:198;
      targetLiquid.insertAdjacentHTML('beforeend','<path class="inside-stream" d="M50 12Q'+(50+wave*.6)+' 55 50 '+surfaceY+'" fill="none" stroke="'+COLORS[res.color][0]+'" stroke-width="3.4" opacity=".86"/><ellipse class="liquid-impact" cx="50" cy="'+(surfaceY+1)+'" rx="'+(7+wave*1.5)+'" ry="'+(1.5+Math.abs(wave)*.6)+'" fill="none" stroke="#fff" stroke-width="1.4" opacity=".46"/>');
      if(now-lastNoise>210){lastNoise=now;K.audio.noise({dur:.24,vol:.07,filter:650,q:.5,type:'lowpass'});}
    }
    const drop=stream.querySelector('.pour-drop');drop.style.display='none';
    if(!flowing&&elapsed>=flowEnd&&elapsed<flowEnd+dripTime){const f=(elapsed-flowEnd)/dripTime;stream.style.opacity=1;stream.querySelectorAll('path').forEach(p=>p.style.visibility='hidden');drop.style.display='';drop.setAttribute('cx',mix(x,opening.x,f));drop.setAttribute('cy',mix(y,opening.y,f*f));drop.setAttribute('r',Math.max(1.3,sr.width*.022));}
    if(elapsed<duration)raf=requestAnimationFrame(frame);else finish();
  }
  frame(lastFrame);
}
function undo(){if(blocked()||!history.length)return;board=history.pop();moves=Math.max(0,moves-1);undos++;selected=-1;hintTo=-1;render();say('Langkah terakhir dibatalkan.');playSound();save();}
function hint(){if(blocked())return;busy=true;updateHUD();say('Mencari langkah untuk susunan ini...');const token=epoch;hintTimer=setTimeout(()=>{if(token!==epoch)return;busy=false;if(mode!=='play')return;const m=E.hint(board,{maxNodes:18000,maxMs:90});if(m){selected=m.from;hintTo=m.to;hints++;render();say('Tuang botol '+(m.from+1)+' ke botol '+(m.to+1)+'.');save();}else{updateHUD();say('Belum menemukan jalan. Batal langkah terakhir atau coba ulang.');}},30);}
function sheet(html,focusId){hideSheets();$('sheetContent').innerHTML=html;$('sheet').hidden=false;returnFocus=document.activeElement;const focus=focusId?$(focusId):$('sheet').querySelector('.panel');focus.focus({preventScroll:true});}
function closeSheet(){$('sheet').hidden=true;if(mode==='pause'){mode='play';busy=false;render();}if(returnFocus&&returnFocus.isConnected)returnFocus.focus({preventScroll:true});}
function pause(){if(mode!=='play')return;finishPour();if(mode!=='play')return;clearTimeout(hintTimer);busy=false;save();mode='pause';sheet('<h2 id="sheetTitle">Istirahat dulu</h2><p>'+(saveOk?'Permainanmu tersimpan.<br>Tidak ada waktu yang mengejar.':'Penyimpanan tidak tersedia.<br>Tetap di tab ini agar permainan tidak hilang.')+'</p><button id="sContinue" class="gold">LANJUT BERMAIN</button><button id="sPatterns" class="switch-row text-btn" role="switch" aria-checked="'+patterns+'">Angka pada warna <span>'+(patterns?'Aktif':'Nonaktif')+'</span></button><button id="sPourMotion" class="switch-row text-btn" role="switch" aria-checked="'+fullPour()+'">Gerakan botol <span>'+(fullPour()?'Aktif':'Tenang')+'</span></button><button id="sSettings" class="secondary">Suara &amp; musik</button><button id="sMenu" class="text-btn">Kembali ke menu</button>','sContinue');}
function confirmRestart(){if(blocked())return;mode='pause';sheet('<h2 id="sheetTitle">Mulai dari awal?</h2><p>Susunan botol tetap sama. Langkah saat ini akan dihapus.'+(kind==='daily'?' Pengulangan dihitung sebagai latihan.':'')+'</p><button id="sContinue" class="gold">LANJUT BERMAIN</button><button id="sRestart" class="secondary">Mulai ulang</button>','sContinue');}
function daily(){const today=K.dateKey(),d=ST.get('daily',null),used=d&&d.date===today&&d.started,r=readSaved('daily');sheet('<h2 id="sheetTitle">Warna hari ini</h2><p>'+today+'<br>Susunan yang sama untuk semua pemain.<br>Satu percobaan resmi per hari.</p><button id="sDaily" class="gold">'+(r?'LANJUT HARIAN':used?'MAIN LATIHAN':'MAIN HARIAN')+'</button><p>'+(used?(d.done?'Skor Harian kamu: '+d.score:'Percobaan resmi hari ini sudah dimulai.'): 'Tanpa batas waktu. Bisa dilanjutkan nanti.')+'</p>','sDaily');}
function startDaily(){const date=K.dateKey(),s=((8<<24)|(K.dailySeed(SLUG)&0xffffff))>>>0,d=ST.get('daily',null),r=readSaved('daily',s);if(r){start('daily',8,s,r);return;}const used=d&&d.date===date&&d.started;if(!used)ST.set('daily',{date,started:true,done:false,seed:s});start(used?'practice':'daily',8,s,used?readSaved('practice',s):null);}
function computeScore(){return Math.max(100,Math.round((1000+generated.colors*150)*Math.min(1.25,generated.par/Math.max(1,moves))-hints*55-undos*12));}
function complete(){if(mode!=='play')return;mode='result';busy=false;selected=-1;const saved=ST.get(key(),null);if(saved&&saved.seed===seed)ST.set(key(),null);if(kind==='daily'&&runDate!==K.dateKey())kind='practice';const score=computeScore(),stars=hints===0&&moves<=generated.par*1.15?3:hints<=2&&moves<=generated.par*1.8?2:1,oldBest=+ST.get('best',0)||0,best=Math.max(oldBest,score);ST.set('best',best);if(kind==='normal')ST.set('level',Math.max(boundedLevel(ST.get('level',1)),Math.min(255,level+1)));if(kind==='daily')ST.set('daily',{date:runDate,started:true,done:true,seed,score});const progress=K.progress.record({game:SLUG,score,mutu:stars/3,papan:''});lastResult={seed,score,level,stars};ST.set('last',lastResult);$('stars').innerHTML=Array.from({length:3},(_,i)=>'<span'+(i>=stars?' class="dim"':'')+'>\u2605</span>').join('');$('stars').setAttribute('aria-label',stars+' dari 3 bintang');$('resultTitle').textContent=kind==='chal'?(score>challenge.score?'Kamu unggul!':score===challenge.score?'Skor seri!':'Belum mengalahkan teman'):'Rapi banget!';$('resultNote').textContent=kind==='chal'?(score<challenge.score?'Kurang '+(challenge.score-score+1)+' untuk unggul. Target '+challenge.score:'Skor teman '+challenge.score):kind==='daily'?'Harian selesai. Sampai besok!':kind==='practice'?'Latihan Harian selesai.':'Level '+level+' selesai. Siap warna berikutnya?';$('scoreValue').textContent=0;clearInterval(countTimer);if(reduced())$('scoreValue').textContent=score;else{let began=performance.now();countTimer=setInterval(()=>{const f=Math.min(1,(performance.now()-began)/650);$('scoreValue').textContent=Math.round(score*(1-Math.pow(1-f,3)));if(f===1)clearInterval(countTimer);},30);}$('bestNote').textContent=score>oldBest?'Rekor baru! '+best:score===best?'Menyamai rekor: '+best:'Kurang '+(best-score)+' untuk rekor '+best;$('bestBar').style.width=Math.round(score/best*100)+'%';$('statMoves').textContent=moves;$('statHints').textContent=hints;$('statColors').textContent=generated.colors;$('xpNote').textContent='+'+progress.gain+' XP \u00b7 Lv '+progress.level+' \u00b7 '+progress.streak+' hari berturut-turut';$('rAgain').textContent=kind==='normal'?'LEVEL BERIKUTNYA':'MAIN LAGI';$('result').hidden=false;$('rAgain').focus({preventScroll:true});playSound(true);if(score>oldBest&&!reduced())K.ui.confetti(55);K.vibrate([30,40,50]);}
function again(){if(mode!=='result'||$('result').hidden)return;const k=kind==='daily'?'practice':kind,l=kind==='normal'?Math.min(255,level+1):level;start(k,l,k==='normal'?freshSeed(l):seed);}
function share(){const r=lastResult||ST.get('last',null);if(!r)return;const url=K.challengeLink(SLUG,r.seed,r.score),text='Aku dapat '+r.score+' di Sortir Cairan! Coba susunan yang sama dan kalahkan skorku.';K.share({title:'Sortir Cairan',text,url});}
function challenges(){const r=lastResult||ST.get('last',null);sheet('<h2 id="sheetTitle">Tantang teman</h2><p>Main dulu sampai semua warna rapi. Setelah itu, bagikan skormu. Teman mendapat susunan botol yang sama.</p>'+(r?'<button id="sShare" class="gold">BAGIKAN SKOR '+r.score+'</button>':'<button id="sMain" class="gold">MAIN SEKARANG</button>')+'<p>Tantangan lewat tautan. Tidak perlu menunggu lawan.</p>',r?'sShare':'sMain');}
$('bMain').onclick=main;$('bDaily').onclick=daily;$('bChallenge').onclick=challenges;$('bSettings').onclick=()=>{playSound();window.SortirCairanSetelan();};$('bPause').onclick=pause;$('bUndo').onclick=undo;$('bHint').onclick=hint;$('bRestart').onclick=confirmRestart;$('sheetClose').onclick=closeSheet;
$('board').onclick=e=>{const b=e.target.closest('[data-i]');if(b)select(+b.dataset.i);};
$('sheet').addEventListener('click',e=>{const b=e.target.closest('button');if(!b||$('sheet').hidden)return;playSound();switch(b.id){case'sContinue':closeSheet();break;case'sMenu':title();break;case'sSettings':window.SortirCairanSetelan();break;case'sPourMotion':pourMotion=!fullPour();ST.set('pourMotion',pourMotion);b.setAttribute('aria-checked',pourMotion);b.querySelector('span').textContent=pourMotion?'Aktif':'Tenang';break;case'sPatterns':patterns=!patterns;ST.set('patterns',patterns);b.setAttribute('aria-checked',patterns);b.querySelector('span').textContent=patterns?'Aktif':'Nonaktif';render();break;case'sRestart':start(kind==='daily'?'practice':kind,level,seed);break;case'sDaily':startDaily();break;case'sShare':share();break;case'sMain':main();break;}});
$('rAgain').onclick=again;$('rShare').onclick=()=>{if(mode==='result'&&!$('result').hidden)share();};$('rMenu').onclick=()=>{if(mode==='result'&&!$('result').hidden)title();};
document.addEventListener('keydown',e=>{const settings=document.querySelector('.dk-overlay:not([hidden])'),active=settings||(!$('result').hidden?$('result'):!$('sheet').hidden?$('sheet'):null);if(active){if(e.key==='Escape'){e.preventDefault();if(settings){settings.hidden=true;const b=mode==='pause'?$('sSettings'):$('bSettings');if(b)b.focus();}else if(active===$('sheet'))closeSheet();return;}if(e.key==='Tab'){const list=Array.from(active.querySelectorAll('button,a,input,[tabindex="0"]')).filter(n=>!n.disabled&&n.getClientRects().length);if(!list.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&(document.activeElement===first||!list.includes(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!list.includes(document.activeElement))){e.preventDefault();first.focus();}}return;}if(e.key==='Escape'&&mode==='play'){e.preventDefault();pause();return;}if(/^Arrow/.test(e.key)&&mode==='play'){const list=Array.from($('board').querySelectorAll('button')),i=list.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const step=e.key==='ArrowRight'||e.key==='ArrowDown'?1:-1;list[(i+step+list.length)%list.length].focus();}});
let resizeTimer;window.addEventListener('resize',()=>{finishPour();clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(mode==='play'||mode==='pause')render();},60);});document.addEventListener('visibilitychange',()=>{if(document.hidden){finishPour();save();}});window.addEventListener('pagehide',()=>{finishPour();save();});
window.SortirCairanGame=Object.freeze({snapshot:()=>({mode,kind,level,seed,moves,hints,undos,busy,selected,board:E.clone(board),initial:generated?E.clone(generated.board):[],solution:generated?generated.solution.map(m=>({...m})):[]}),score:computeScore});
function uji(){const lines=[];let failed=false;function check(v,n){if(!v)failed=true;lines.push((v?'OK ':'GAGAL ')+n);}const a=[[0,1,1],[1,1,1],[]],copy=JSON.stringify(a),p=E.pour(a,0,1);check(p&&p.count===1&&p.board[0].length===2,'kapasitas membatasi tuang');check(JSON.stringify(a)===copy,'tuang tidak mengubah input');check(!E.pour([[0],[1]],0,1),'warna berbeda ditolak');check(!E.pour([[0],[0,0,0,0]],0,1),'botol penuh ditolak');check(!E.pour([[],[1]],0,1),'botol kosong ditolak');check(!E.pour([[0],[]],0,0),'menuang ke diri sendiri ditolak');check(!E.isSolved([[0,0],[]]),'botol parsial belum selesai');check(E.isSolved([[0,0,0,0],[]]),'botol sewarna penuh selesai');for(let l=1;l<=24;l++){const g=E.generate(l,(l<<24)|1234);let b=g.board,ok=b.filter(t=>!t.length).length===2;for(const m of g.solution){const r=E.pour(b,m.from,m.to);if(!r){ok=false;break;}b=r.board;}check(ok&&E.isSolved(b),'level '+l+' punya solusi legal');}check(JSON.stringify(E.generate(8,135).board)===JSON.stringify(E.generate(8,135).board),'seed yang sama menghasilkan susunan sama');check(seedLevel(freshSeed(24))===24,'level tersimpan dalam tautan tantangan');const pre=document.createElement('pre');pre.id='uji';pre.textContent=(failed?'UJI GAGAL':'UJI LULUS')+'\n'+lines.join('\n');document.body.appendChild(pre);}
if(Q.get('icon')==='1'){document.body.classList.add('icon');$('hero').innerHTML=[[2,0,1,1],[0,2,2,0],[3,1,3,3]].map(a=>bottleSVG(a)).join('');}if(Q.get('cover')==='1')document.body.classList.add('cover');title();if(Q.get('demo')==='1'){const l=boundedLevel(Q.get('level')||8);start('normal',l,((l<<24)|0xabc)>>>0);}if(Q.get('uji')==='1')uji();
})();
